[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "euchre_bots"
version = "1.0.0"
dependencies = []

[tool.setuptools.packages]
find = {where = ["src"]}